language: c
cache: cargo
sudo: required

os:
  - linux
  - osx

before_install:
  - if [[ $TRAVIS_OS_NAME = "linux" ]]; then
      echo "deb-src http://archive.ubuntu.com/ubuntu xenial main restricted universe multiverse" | sudo tee -a /etc/apt/sources.list;
      sudo apt-get update -q;
      sudo apt-get build-dep -y libpng16-16;
      sudo apt-get source -b -t xenial libpng16-16;
    fi

script:
#  - ./configure --with-lcms2
#  - make
#  - make test
#  - sudo make install
  - cargo build --release --features=sse,lcms2-static,openmp-static
  - cp ./target/release/pngquant $TRAVIS_BUILD_DIR/$TRAVIS_OS_NAME-pngquant

deploy:
  provider: releases
  tag_name: $TRAVIS_TAG
  target_commitish: $TRAVIS_COMMIT
  name: $TRAVIS_TAG
  overwrite: true
  skip_cleanup: true
  api_key: $github_token
  file_glob: true
  file:
    - $TRAVIS_BUILD_DIR/linux-pngquant
    - $TRAVIS_BUILD_DIR/osx-pngquant
  on:
    tags: true
